-- CrisisGrid (AFAD Uygulaması) Supabase Veritabanı Şeması
-- Bu dosya, projeyi kendi Supabase hesabınızda kurmak için gereken SQL komutlarını içerir.

-- ==========================================
-- 1. YARDIM ÇAĞRILARI TABLOSU (reports)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL DEFAULT 'victim',
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    details TEXT NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    priority TEXT NOT NULL DEFAULT 'P3', -- P1 (Kritik), P2 (Acil), P3 (Hafif)
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Hızlı sorgular için indeksler
CREATE INDEX IF NOT EXISTS reports_phone_idx ON public.reports (phone);
CREATE INDEX IF NOT EXISTS reports_timestamp_idx ON public.reports (timestamp DESC);

-- ==========================================
-- 2. GÖNÜLLÜ VE KAYNAK TABLOSU (volunteers)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL DEFAULT 'volunteer',
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    vehicle TEXT,
    training TEXT,
    resources TEXT,
    details TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Hızlı sorgular için indeksler
CREATE INDEX IF NOT EXISTS volunteers_phone_idx ON public.volunteers (phone);
CREATE INDEX IF NOT EXISTS volunteers_timestamp_idx ON public.volunteers (timestamp DESC);

-- ==========================================
-- 3. RLS (Row Level Security) POLİTİKALARI
-- ==========================================
-- Geliştirme aşaması için Public (Anonim) okuma/yazma izinleri
-- NOT: Canlı ortamda bu kuralların kimlik doğrulamasına (Auth) bağlanması önerilir.

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read for reports" ON public.reports FOR SELECT USING (true);
CREATE POLICY "Allow public insert for reports" ON public.reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete for reports" ON public.reports FOR DELETE USING (true);

ALTER TABLE public.volunteers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read for volunteers" ON public.volunteers FOR SELECT USING (true);
CREATE POLICY "Allow public insert for volunteers" ON public.volunteers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete for volunteers" ON public.volunteers FOR DELETE USING (true);
